(function () {
"use strict";
function renderLayerManager(){layerManager.replaceChildren();if(!selectedObject||!selectedObject.isConnected||!selectedObject.classList.contains("planter-composite")||!selectedObject._pot){layerManager.hidden=true;return}layerManager.hidden=false;const title=document.createElement("div");title.className="layer-manager-title";title.textContent="Pot components";const hint=document.createElement("div");hint.className="layer-manager-hint";const fit=selectedObject._plant?plantFitMessage(selectedObject._plant,selectedObject._pot):"";hint.textContent="Choose a layer, then tap inventory to replace it. Separate moves the item back onto the plan."+(fit?" "+fit:"");layerManager.append(title,hint);[["plant","Plant",selectedObject._plant],["pot","Pot",selectedObject._pot],["pebbles","Pebbles",selectedObject._stones]].forEach(entry=>{if(!entry[2])return;const row=document.createElement("div");row.className="layer-row";const choose=document.createElement("button");choose.type="button";choose.className="layer-target"+(selectedLayer===entry[0]?" active":"");choose.textContent=entry[1]+": "+entry[2].name;choose.addEventListener("click",()=>{selectedLayer=entry[0];renderLayerManager()});const separate=document.createElement("button");separate.type="button";separate.className="layer-action";separate.textContent="Separate";separate.setAttribute("aria-label","Separate "+entry[1]);separate.addEventListener("click",()=>separateLayer(entry[0]));const remove=document.createElement("button");remove.type="button";remove.className="layer-action remove";remove.textContent="×";remove.setAttribute("aria-label","Remove "+entry[1]);remove.addEventListener("click",()=>removeLayer(entry[0]));row.append(choose,separate,remove);layerManager.appendChild(row)})}
function splitPot(object,includePot){const x=Number(object.dataset.x),y=Number(object.dataset.y),plant=object._plant,stones=object._stones,pot=object._pot;object.remove();selectObject(null);if(includePot&&pot)addLoose(pot,{x:Math.max(5,x-9),y:Math.min(93,y+8)});if(plant)addLoose(plant,{x:Math.min(95,x+9),y:Math.min(93,y+8)});if(stones)addLoose(stones,{x:Math.max(5,x-9),y:Math.max(7,y-8)})}
function separateLayer(layer){if(!selectedObject||!selectedObject.classList.contains("planter-composite"))return;const object=selectedObject,product=layer==="plant"?object._plant:layer==="pot"?object._pot:object._stones;if(!product)return;if(layer==="pot"){splitPot(object,true);return}if(layer==="plant")object._plant=null;else object._stones=null;addLoose(product,{x:Math.min(95,Number(object.dataset.x)+9),y:Math.min(93,Number(object.dataset.y)+8)});updatePlanter(object,object._plant,object._pot,object._stones);selectedLayer="";renderLayerManager()}
function removeLayer(layer){if(!selectedObject||!selectedObject.classList.contains("planter-composite"))return;const object=selectedObject;if(layer==="pot"){splitPot(object,false);return}if(layer==="plant")object._plant=null;else object._stones=null;updatePlanter(object,object._plant,object._pot,object._stones);selectedLayer="";renderLayerManager()}
const css = [
"#canvasArea{background:#e9eee8!important;overflow:hidden!important}",
".template-card{background-size:contain!important;background-position:center!important;background-repeat:no-repeat!important;border-color:rgba(32,73,52,.24);background-color:#e8ebe6}",
".template-card:before{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 35%,rgba(0,0,0,.55));pointer-events:none}",
".garden-plan{position:absolute;inset:62px 4% 64px;overflow:hidden;border:0;border-radius:0;box-shadow:none;transform-origin:center;transition:transform .4s,filter .4s;background-color:transparent;background-size:contain;background-position:center;background-repeat:no-repeat;touch-action:none;cursor:grab}",
".garden-plan.is-panning{transition:none;cursor:grabbing}",
".garden-plan:after{display:none}",
".plan-grid{display:none!important}",
".ground-feature{position:absolute;pointer-events:none;z-index:2;border:3px solid rgba(255,255,255,.56);box-shadow:0 5px 12px rgba(30,45,30,.18),inset 0 0 0 2px rgba(44,69,41,.1);border-radius:7px}",
".feature-bed{background:repeating-linear-gradient(135deg,#69492e 0 8px,#775234 8px 16px)}",
".feature-path{background-color:#bcb9ad;background-image:repeating-linear-gradient(0deg,transparent 0 19px,rgba(74,70,60,.3) 19px 21px),repeating-linear-gradient(90deg,transparent 0 25px,rgba(74,70,60,.28) 25px 27px)}",
".feature-deck{background:repeating-linear-gradient(0deg,#c99e6f 0 19px,#986b43 20px 22px)}",
".feature-hedge{border:0;border-radius:999px;background:linear-gradient(90deg,#416b3e,#79a44f,#416b3e);box-shadow:0 4px 7px rgba(29,55,27,.35)}",
".plan-toolbar{position:absolute;z-index:30;top:10px;left:50%;transform:translateX(-50%);display:flex;align-items:center;gap:4px;padding:5px;border:1px solid rgba(255,255,255,.8);border-radius:999px;background:rgba(255,255,255,.92);box-shadow:0 5px 18px rgba(20,45,31,.15);backdrop-filter:blur(12px)}",
".plan-toolbar button{border:0;border-radius:999px;padding:8px 13px;background:transparent;color:#496154;font:600 11px Inter,Arial,sans-serif;cursor:pointer}",
".plan-toolbar button.active{background:#0e6c4a;color:white;box-shadow:0 2px 5px rgba(8,56,38,.22)}",
".plan-toolbar .plan-zoom{width:32px;height:32px;padding:0;font-size:18px;background:#f0f3ef}",
".plan-scale{position:absolute;z-index:25;bottom:10px;left:50%;transform:translateX(-50%);display:flex;color:#3e5147;font:600 9px Inter,Arial,sans-serif;pointer-events:none}",
".plan-scale span{position:relative;width:var(--scale-meter-width,48px);text-align:center;padding-top:8px}",
".plan-scale span:before{content:'';position:absolute;top:3px;left:0;right:0;height:3px;border-left:1px solid #43594a;border-right:1px solid #43594a;border-top:2px solid #43594a}",
".garden-object{position:absolute;z-index:8;width:var(--object-width,90px);height:calc(var(--object-width,90px)*1.28);transform:translate(-50%,-62%);cursor:grab;touch-action:none;user-select:none;filter:drop-shadow(0 8px 7px rgba(16,37,25,.3))}",
".garden-object:before{content:'';position:absolute;z-index:8;left:50%;top:50%;width:max(44px,100%);height:max(44px,100%);transform:translate(-50%,-50%);background:transparent;touch-action:none}",
".garden-object:active{cursor:grabbing}.garden-object.selected{filter:drop-shadow(0 0 5px #ffe28a) drop-shadow(0 8px 7px rgba(16,37,25,.38))}",
".garden-object img{pointer-events:none;-webkit-user-drag:none}",
".planter-shadow{position:absolute;z-index:0;bottom:0;left:10%;width:80%;height:13%;border-radius:50%;background:radial-gradient(ellipse,rgba(22,34,24,.35),transparent 70%)}",
".planter-side{position:absolute;inset:0;isolation:isolate}",
".planter-plant{position:absolute;z-index:2;bottom:24%;left:-6%;width:112%;height:112%;object-fit:contain;object-position:center bottom;transform:scale(var(--plant-scale,1));transform-origin:center bottom;filter:drop-shadow(0 4px 4px rgba(16,34,19,.24))}",
".planter-pot{position:absolute;z-index:4;bottom:0;left:4%;width:92%;height:79%;object-fit:contain;object-position:center bottom;filter:drop-shadow(0 7px 6px rgba(25,27,20,.34))}",
".pebble-wrap{position:absolute;z-index:3;left:29%;bottom:51%;width:42%;height:19%;overflow:hidden;border-radius:50%;pointer-events:none}",
".planter-pebbles{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;clip-path:ellipse(49% 46% at 50% 50%);transform:scale(var(--pebble-scale,1));transform-origin:center;filter:drop-shadow(0 1px 2px rgba(20,20,15,.38))}",
".planter-top-view{display:none;position:absolute;inset:0;align-items:flex-start;justify-content:center;padding-top:5%}",
".top-pot-rim{position:relative;width:88%;aspect-ratio:1;border-radius:50%;overflow:hidden;border:clamp(1px,calc(var(--object-width,90px)*.08),7px) solid #a7623f;background:radial-gradient(circle at 48% 45%,#342719 0 55%,#75452e 57% 66%,#d18a5e 68% 77%,#9d593d 79%);box-shadow:inset 0 3px 7px rgba(255,235,193,.65),0 5px 8px rgba(20,35,22,.26)}",
".top-plant{position:absolute;inset:2% 5%;width:90%;height:96%;object-fit:cover;object-position:center 12%;clip-path:circle(46% at 50% 50%);transform:scale(var(--plant-scale,1))}",
".top-pebbles{position:absolute;z-index:2;left:23%;top:57%;width:54%;height:24%;object-fit:cover;clip-path:ellipse(50% 48% at 50% 50%);transform:scale(var(--pebble-scale,1));transform-origin:center;opacity:.9}",
".view-2d .planter-side{display:none}.view-2d .planter-top-view{display:flex}",
".view-2d .garden-object{height:var(--object-width,90px);transform:translate(-50%,-52%);filter:drop-shadow(0 3px 3px rgba(20,40,25,.28))}",
".planter-label{position:absolute;left:50%;bottom:-23px;transform:translateX(-50%);max-width:165%;padding:2px 6px;border-radius:20px;background:rgba(255,255,255,.92);color:#34483a;font:600 9px Inter,Arial,sans-serif;white-space:nowrap;box-shadow:0 1px 4px rgba(0,0,0,.15);pointer-events:none}",
".object-remove{position:absolute;top:-15px;right:-15px;z-index:11;width:24px;height:24px;border:2px solid #fff;border-radius:50%;color:white;background:#ba1a1a;opacity:0;cursor:pointer;box-shadow:0 2px 5px rgba(0,0,0,.25)}",
".garden-object:hover .object-remove,.garden-object.selected .object-remove{opacity:1}",
".plan-instructions{position:absolute;z-index:22;left:10px;bottom:9px;max-width:220px;padding:7px 9px;border-radius:10px;background:rgba(255,255,255,.92);color:#34483a;font:600 10px Inter,Arial,sans-serif;pointer-events:none}",
".garden-layer-manager{position:absolute;z-index:29;right:10px;bottom:42px;width:min(300px,46%);max-height:48%;overflow:auto;padding:10px;border:1px solid rgba(20,70,45,.2);border-radius:14px;background:rgba(255,255,255,.96);box-shadow:0 7px 20px rgba(19,43,26,.2);font:500 10px Inter,Arial,sans-serif;color:#274332}",
".layer-manager-title{font-weight:700;font-size:11px;margin-bottom:3px}.layer-manager-hint{color:#59685e;margin-bottom:6px;line-height:1.35}.layer-row{display:flex;align-items:center;gap:4px;padding:4px 0;border-top:1px solid #e8eee9}",
".layer-target{flex:1;min-width:0;border:0;border-radius:7px;padding:6px 5px;text-align:left;background:#f1f5f1;color:#294433;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:600 10px Inter,Arial,sans-serif}.layer-target.active{background:#d7f0df;outline:1px solid #3c885e}.layer-action{border:0;border-radius:7px;padding:6px 7px;background:#e7eee8;color:#355541;font:700 9px Inter,Arial,sans-serif;white-space:nowrap}.layer-action.remove{color:#a42828;background:#fff0ed}",
".loose-item{position:absolute;width:100%;height:100%;object-fit:contain}.loose-item.type-pebbles{transform:perspective(80px) rotateX(22deg) scaleY(.72)}",
"@media(max-width:850px){.garden-plan{inset:62px 3% 64px}.plan-instructions{left:8px;right:auto;bottom:6px;max-width:45%;font-size:9px}.garden-layer-manager{right:8px;bottom:35px;width:50%;max-height:48%}.plan-toolbar button{padding:7px 10px}.plan-scale span{width:var(--scale-meter-width,36px)}.planter-label{font-size:8px}}",
"@media(max-width:520px){.plan-toolbar{gap:1px}.plan-toolbar button{padding:7px 8px;font-size:10px}.plan-toolbar .plan-zoom{width:28px;height:28px}}"
].join("\n");
const style = document.createElement("style"); style.textContent=css; document.head.appendChild(style);
const canvasArea=document.getElementById("canvasArea"), placeholder=document.getElementById("canvasPlaceholder"), grid=document.getElementById("dimensionGrid"), loader=document.getElementById("canvasLoader"), aiButton=document.getElementById("aiDecorateBtn");
const plan=document.createElement("div"); plan.id="gardenPlan"; plan.className="garden-plan theme-lawn"; plan.style.display="none"; grid.classList.add("plan-grid"); plan.appendChild(grid); canvasArea.insertBefore(plan,loader);
const toolbar=document.createElement("div"); toolbar.className="plan-toolbar"; toolbar.setAttribute("aria-label","Garden plan view controls"); toolbar.innerHTML='<button type="button" class="view-button active" data-view="2d">2D Plan</button><button type="button" class="view-button" data-view="3d">Angled View</button><button type="button" class="plan-zoom" data-zoom="out" aria-label="Zoom out">-</button><button type="button" class="plan-zoom" data-zoom="in" aria-label="Zoom in">+</button>'; canvasArea.appendChild(toolbar);
const scale=document.createElement("div"); scale.className="plan-scale"; scale.innerHTML="<span>0 m</span><span>1 m</span><span>2 m</span><span>3 m</span><span>4 m</span>"; canvasArea.appendChild(scale);
const instruction=document.createElement("div"); instruction.className="plan-instructions"; instruction.textContent="Drag items to arrange. Drop a plant or pebbles onto a pot to place them inside."; canvasArea.appendChild(instruction);
const layerManager=document.createElement("div"); layerManager.className="garden-layer-manager"; layerManager.hidden=true; canvasArea.appendChild(layerManager);
let selectedObject=null,selectedLayer="",currentView="2d",planZoom=1,manualCount=0,planPanX=0,planPanY=0,panState=null;
function normCategory(value){const c=String(value||"").toLowerCase().trim();if(c.indexOf("pot")>=0)return"pots";if(c.indexOf("pebble")>=0||c.indexOf("stone")>=0)return"pebbles";if(c.indexOf("outdoor")>=0)return"outdoor";if(c.indexOf("indoor")>=0)return"indoor";if(c.indexOf("supply")>=0||c.indexOf("fertil")>=0||c.indexOf("soil")>=0)return"supplies";return c}
function inventoryProduct(name,category){if(!name||!Array.isArray(PRODUCTS))return null;const wanted=normCategory(category);return PRODUCTS.find(p=>p.name.toLowerCase()===String(name).toLowerCase()&&normCategory(p.category)===wanted)||null}
function firstIn(category){return(Array.isArray(PRODUCTS)?PRODUCTS:[]).find(p=>normCategory(p.category)===category)||null}
function localImage(product){const path=product&&product.image_url?String(product.image_url):"";return/^IMAGE\//i.test(path)?path:"IMAGE/logo.png"}
// Inventory has no measured height/spread fields yet; use size tags and known growth habits against the displayed meter ruler.
function planPixelsPerMeter(){return window.matchMedia("(max-width: 850px)").matches?36:48}
function sizeTier(name){const t=String(name||"").toLowerCase();if(/\b(extra\s*large|xl)\b/.test(t))return"extra large";if(/\blarge\b/.test(t))return"large";if(/\bmedium\b/.test(t))return"medium";if(/\bsmall\b/.test(t))return"small";if(/\b(bird of paradise|horse tail|pinugo|yellow bell|pandanus|cypress|eugenia|thai bamboo|alucaria|araucaria|cochinchinensis|bucida|golden betcha|hawaiian ti|san francisco|ti plant|selloum)\b/.test(t))return"large";if(/\b(aglaonema|calathea|peace lily|orchid|anthurium|bromeliad|ruellia|forget-me-not|yellow irish|bakya|picarra|copea|zig zag)\b/.test(t))return"small";return"medium"}
function plantSpreadMeters(name){const t=String(name||"").toLowerCase(),tier=sizeTier(t),base={small:.22,medium:.34,large:.56,"extra large":.78}[tier]||.34;if(/\b(bird of paradise|horse tail|pandanus|cypress|thai bamboo|alucaria|araucaria|hawaiian ti|ti plant|san francisco)\b/.test(t))return base*.82;if(/\b(selloum|bucida|eugenia|santan|bottle brush|pandakaki|triangularis|maki|havetia|golden betcha)\b/.test(t))return base*1.12;return base}
function namedPotInches(name){const t=String(name||"").toLowerCase().replace(/[″”]/g,'"'),m=t.match(/(\d+(?:\.\d+)?)\s*-?\s*(?:inch(?:es)?\b|in\b|["])/i);if(m)return Number(m[1]);if(/\b(extra\s*large|xl)\b/.test(t))return 20;if(/\blarge\b/.test(t))return 16;if(/\bmedium\b/.test(t))return 10;if(/\bsmall\b/.test(t))return 6;if(/assorted/.test(t))return 12;return 10}
function potDiameterMeters(name){return namedPotInches(name)*.0254}
function planterContainerWidth(pot){const artFill=currentView==="2d" ? .88 : .92*.47;return Math.max(8,Math.round(potDiameterMeters(pot&&pot.name)*planPixelsPerMeter()/artFill))}
function plantFitMessage(plant,pot){const tier=sizeTier(plant&&plant.name),minimum={small:6,medium:8,large:12,"extra large":16}[tier]||8,actual=namedPotInches(pot&&pot.name);return actual>=minimum?"Estimated fit: the "+actual+"-inch pot suits a "+tier+" plant.":"Estimated fit: try a pot of at least "+minimum+" inches for this "+tier+" plant."}
function measuredWidth(name,category){const t=String(name||"").toLowerCase().replace(/[″”]/g,'"'),c=normCategory(category),m=t.match(/(\d+(?:\.\d+)?)\s*-?\s*(?:inch(?:es)?\b|in\b|["])/i),ppm=planPixelsPerMeter();if(c==="pots")return Math.max(10,Math.round(potDiameterMeters(t)*ppm/.47));if(c==="indoor"||c==="outdoor")return Math.max(10,Math.round(plantSpreadMeters(t)*ppm));if(c==="pebbles")return Math.max(8,Math.round((m?Number(m[1])*.0254:.28)*ppm));if(c==="supplies")return Math.max(10,Math.round(.25*ppm));return Math.max(10,Math.round(.3*ppm))}
function nextPosition(index){const spots=[[38,38],[62,38],[50,50],[38,62],[62,62],[50,68],[34,50],[66,50]];return spots[index%spots.length]}
function setImage(wrap,product,className){wrap.textContent="";if(!product)return;const img=document.createElement("img");img.className=className;img.src=localImage(product);img.alt=product.name;img.draggable=false;img.onerror=function(){img.src="IMAGE/logo.png"};wrap.appendChild(img)}
function objectParts(object){if(object.classList.contains("planter-composite"))return{plant:object._plant||null,pot:object._pot||null,pebbles:object._stones||null};const product=object._product;if(!product)return{plant:null,pot:null,pebbles:null};const type=normCategory(product.category);if(type==="pots")return{plant:null,pot:product,pebbles:null};if(type==="pebbles")return{plant:null,pot:null,pebbles:product};if(type==="indoor"||type==="outdoor")return{plant:product,pot:null,pebbles:null};return{plant:null,pot:null,pebbles:null}}
function findObjectAt(x,y,except){const nodes=Array.from(plan.querySelectorAll(".garden-object")).filter(n=>n!==except).sort((a,b)=>Number(b.style.zIndex||0)-Number(a.style.zIndex||0)),targetRadius=22*planZoom*(currentView==="3d"?.9:1);return nodes.find(n=>{const r=n.getBoundingClientRect(),padX=Math.max(0,targetRadius-r.width/2),padY=Math.max(0,targetRadius-r.height/2);return x>=r.left-padX&&x<=r.right+padX&&y>=r.top-padY&&y<=r.bottom+padY})||null}
function combineObjects(source,target){const a=objectParts(source),b=objectParts(target),pot=a.pot||b.pot;if(!pot)return false;const x=Number(target.dataset.x),y=Number(target.dataset.y);source.remove();target.remove();const combined=createPlanter(a.plant||b.plant,pot,a.pebbles||b.pebbles,{x,y},true);selectObject(combined);return true}
function selectObject(object){document.querySelectorAll(".garden-object.selected").forEach(n=>n.classList.remove("selected"));selectedObject=object||null;selectedLayer="";if(selectedObject)selectedObject.classList.add("selected");renderLayerManager()}
function makeDraggable(object){let sx=0,sy=0,ox=0,oy=0,moving=false;object.addEventListener("pointerdown",e=>{if(e.target.closest(".object-remove"))return;moving=true;sx=e.clientX;sy=e.clientY;ox=Number(object.dataset.x);oy=Number(object.dataset.y);selectObject(object);object.setPointerCapture(e.pointerId);e.preventDefault()});object.addEventListener("pointermove",e=>{if(!moving)return;const r=plan.getBoundingClientRect();const dx=(e.clientX-sx)/Math.max(.25,r.width/plan.clientWidth),dy=(e.clientY-sy)/Math.max(.25,r.height/plan.clientHeight);object.dataset.x=String(Math.max(4,Math.min(96,ox+dx/plan.clientWidth*100)));object.dataset.y=String(Math.max(5,Math.min(95,oy+dy/plan.clientHeight*100)));object.style.left=object.dataset.x+"%";object.style.top=object.dataset.y+"%"});object.addEventListener("pointerup",e=>{if(!moving)return;moving=false;if(Math.hypot(e.clientX-sx,e.clientY-sy)>10){const target=findObjectAt(e.clientX,e.clientY,object);if(target)combineObjects(object,target)}});object.addEventListener("pointercancel",()=>moving=false)}
function addRemove(object){const b=document.createElement("button");b.type="button";b.className="object-remove";b.setAttribute("aria-label","Remove item");b.textContent="x";b.addEventListener("pointerdown",e=>e.stopPropagation());b.addEventListener("click",e=>{e.stopPropagation();if(selectedObject===object)selectedObject=null;object.remove()});object.appendChild(b)}
function setObjectWidth(object,width){object.style.width=width+"px";object.style.setProperty("--object-width",width+"px")}
function planterWidth(plant,pot){return pot?planterContainerWidth(pot):plant?measuredWidth(plant.name,plant.category):40}
function planterPlantScale(plant,pot){if(!plant||!pot)return 1;const canopyWidth=plantSpreadMeters(plant.name)*planPixelsPerMeter(),baseWidth=planterWidth(plant,pot)*(currentView==="2d" ? .58 : 1.12);return Math.max(.12,Math.min(5,canopyWidth/Math.max(1,baseWidth)))}
function planterPebbleScale(stones,pot){if(!stones||!pot)return 1;const baseRatio=currentView==="2d" ? .88*.54 : .42,baseWidth=planterWidth(null,pot)*baseRatio;return Math.max(.18,Math.min(2.5,measuredWidth(stones.name,"pebbles")/Math.max(1,baseWidth)))}
function updatePlanter(object,plant,pot,stones){object._plant=plant||null;object._pot=pot||null;object._stones=stones||null;setObjectWidth(object,planterWidth(object._plant,object._pot));object.style.setProperty("--plant-scale",String(planterPlantScale(object._plant,object._pot)));object.style.setProperty("--pebble-scale",String(planterPebbleScale(object._stones,object._pot)));setImage(object.querySelector(".plant-wrap"),plant,"planter-plant");setImage(object.querySelector(".pot-wrap"),pot,"planter-pot");setImage(object.querySelector(".pebble-wrap"),stones,"planter-pebbles");setImage(object.querySelector(".top-plant-wrap"),plant,"top-plant");setImage(object.querySelector(".top-stone-wrap"),stones,"top-pebbles");const label=object.querySelector(".planter-label"),parts=[];if(plant)parts.push("Plant");if(pot)parts.push("Pot");if(stones)parts.push("Pebbles");label.textContent=parts.join(" · ")||"Empty pot";object.title=[plant&&plant.name,pot&&pot.name,stones&&stones.name,plant&&pot?plantFitMessage(plant,pot):""].filter(Boolean).join(" · ");renderLayerManager()}
function createPlanter(plant,pot,stones,pos,selectAfter){const p=pos||nextPosition(manualCount++),o=document.createElement("div");o.className="garden-object planter-composite";o.dataset.x=String(p.x==null?p[0]:p.x);o.dataset.y=String(p.y==null?p[1]:p.y);o.dataset.planterSize=pos&&pos.size||"";o.style.left=o.dataset.x+"%";o.style.top=o.dataset.y+"%";setObjectWidth(o,planterWidth(plant,pot));o.style.zIndex=String(8+Math.round(Number(o.dataset.y)/12));o.innerHTML='<div class="planter-shadow"></div><div class="planter-side"><div class="plant-wrap"></div><div class="pot-wrap"></div><div class="pebble-wrap"></div></div><div class="planter-top-view"><div class="top-pot-rim"><div class="top-plant-wrap"></div><div class="top-stone-wrap"></div></div></div><span class="planter-label"></span>';addRemove(o);updatePlanter(o,plant,pot,stones);plan.appendChild(o);makeDraggable(o);o.addEventListener("click",e=>{if(!e.target.closest(".object-remove"))selectObject(o)});if(selectAfter)selectObject(o);return o}
function addLoose(product,pos){const p=pos||nextPosition(manualCount++),cat=normCategory(product.category),o=document.createElement("div");o.className="garden-object loose-component type-"+cat;o._product=product;o.dataset.x=String(p.x==null?p[0]:p.x);o.dataset.y=String(p.y==null?p[1]:p.y);o.style.left=o.dataset.x+"%";o.style.top=o.dataset.y+"%";setObjectWidth(o,measuredWidth(product.name,cat));o.style.zIndex=String(8+Math.round(Number(o.dataset.y)/12));const img=document.createElement("img");img.className="loose-item type-"+cat;img.src=localImage(product);img.alt=product.name;img.draggable=false;img.onerror=()=>img.src="IMAGE/logo.png";const label=document.createElement("span");label.className="planter-label";label.textContent=product.name;o.append(img,label);addRemove(o);plan.appendChild(o);makeDraggable(o);o.addEventListener("click",()=>selectObject(o));return o}
function addToCanvas(imgSrc,name,category){if(!currentThemeName){instruction.textContent="Choose a real garden setting first, then drag or tap an inventory item.";return}const product=inventoryProduct(name,category)||{name:String(name||"Garden item"),category:category,image_url:imgSrc};const type=normCategory(product.category);if(selectedObject&&selectedObject.classList.contains("planter-composite")&&selectedLayer){const match=(selectedLayer==="plant"&&(type==="indoor"||type==="outdoor"))||(selectedLayer==="pot"&&type==="pots")||(selectedLayer==="pebbles"&&type==="pebbles");if(match){if(selectedLayer==="plant")selectedObject._plant=product;if(selectedLayer==="pot")selectedObject._pot=product;if(selectedLayer==="pebbles")selectedObject._stones=product;updatePlanter(selectedObject,selectedObject._plant,selectedObject._pot,selectedObject._stones);renderLayerManager();return selectedObject}}return addLoose(product)}
function renderFeatures(theme){plan.querySelectorAll(".ground-feature").forEach(n=>n.remove());const data=theme==="lawn"?[["feature-bed",{left:"7%",top:"8%",width:"29%",height:"18%"}],["feature-bed",{left:"40%",top:"8%",width:"25%",height:"18%"}],["feature-path",{left:"72%",top:"8%",width:"17%",height:"79%"}],["feature-hedge",{left:"8%",top:"90%",width:"57%",height:"2.5%"}]]:theme==="patio"?[["feature-deck",{left:"9%",top:"14%",width:"54%",height:"70%"}],["feature-hedge",{left:"70%",top:"15%",width:"3%",height:"67%"}],["feature-bed",{left:"75%",top:"18%",width:"17%",height:"24%"}],["feature-bed",{left:"75%",top:"57%",width:"17%",height:"24%"}]]:[["feature-path",{left:"8%",top:"8%",width:"84%",height:"84%"}],["feature-bed",{left:"14%",top:"14%",width:"25%",height:"23%"}],["feature-bed",{left:"61%",top:"63%",width:"24%",height:"22%"}],["feature-hedge",{left:"11%",top:"88%",width:"78%",height:"2.5%"}]];data.forEach(f=>{const n=document.createElement("div");n.className="ground-feature "+f[0];Object.assign(n.style,f[1]);plan.appendChild(n)})}
function loadTemplate(themeType,card){document.querySelectorAll(".template-card").forEach(c=>c.classList.remove("active"));if(card)card.classList.add("active");const scenes={"living-room":{name:"Living Room",image:"IMAGE/template-living-room.svg?v=20261001-clean-scenes",indoor:true},office:{name:"Office",image:"IMAGE/template-office.svg?v=20261001-clean-scenes",indoor:true},bedroom:{name:"Bedroom",image:"IMAGE/template-bedroom.svg?v=20261001-clean-scenes",indoor:true},backyard:{name:"Backyard",image:"IMAGE/planner-backyard-empty.svg?v=20261001-clean-scenes"},garden:{name:"Garden",image:"IMAGE/planner-kitchen-garden-empty.svg?v=20261001-clean-scenes"},resort:{name:"Resort",image:"IMAGE/planner-resort-empty.svg?v=20261001-clean-scenes"},empty_room:{name:"Resort",image:"IMAGE/planner-resort-empty.svg?v=20261001-clean-scenes"},patio:{name:"Backyard",image:"IMAGE/planner-backyard-empty.svg?v=20261001-clean-scenes"},lawn:{name:"Garden",image:"IMAGE/planner-kitchen-garden-empty.svg?v=20261001-clean-scenes"}},scene=scenes[themeType]||scenes.garden;planZoom=1.05;planPanX=0;planPanY=0;plan.className="garden-plan theme-"+themeType;plan.dataset.theme=themeType;plan.style.backgroundImage="url('"+scene.image+"')";plan.style.backgroundSize="contain";plan.style.backgroundPosition="center";plan.style.backgroundRepeat="no-repeat";plan.style.display="block";canvasArea.style.touchAction="none";canvasArea.style.backgroundImage="none";placeholder.style.display="none";grid.style.display="block";plan.querySelectorAll(".ground-feature").forEach(n=>n.remove());currentThemeName=scene.name;instruction.textContent="Drag inventory items onto the plan. Zoom in, then drag empty space with a finger or mouse to pan. Drop plants or pebbles onto a pot to combine them.";aiButton.disabled=false;setView(currentView)}
function clampPlanPan(){const viewFactor=currentView==="3d"?0.9:1,scaleFactor=viewFactor*planZoom,aspect=1200/760,imageWidth=Math.min(plan.offsetWidth,plan.offsetHeight*aspect),imageHeight=Math.min(plan.offsetHeight,plan.offsetWidth/aspect),projectedHeight=imageHeight*scaleFactor*(currentView==="3d"?Math.cos(52*Math.PI/180):1),maxX=Math.max(0,(imageWidth*scaleFactor-canvasArea.clientWidth)/2),maxY=Math.max(0,(projectedHeight-canvasArea.clientHeight)/2);planPanX=Math.max(-maxX,Math.min(maxX,planPanX));planPanY=Math.max(-maxY,Math.min(maxY,planPanY))}
function applyPlanTransform(){clampPlanPan();const meterPixels=planPixelsPerMeter(),viewFactor=currentView==="3d"?0.9:1,scaleFactor=viewFactor*planZoom,screenMeterWidth=meterPixels*scaleFactor,visibleMeters=Math.max(1,Math.min(4,Math.floor((canvasArea.clientWidth-32)/screenMeterWidth)));plan.style.translate=planPanX+"px "+planPanY+"px";plan.style.transform=currentView==="3d"?"perspective(1200px) rotateX(52deg) scale("+scaleFactor+")":"scale("+scaleFactor+")";plan.style.filter=currentView==="3d"?"drop-shadow(0 25px 22px rgba(22,43,28,.25))":"none";plan.style.setProperty("--grid-meter-width",meterPixels+"px");scale.innerHTML=Array.from({length:visibleMeters+1},(_,meter)=>"<span>"+meter+" m</span>").join("");scale.style.setProperty("--scale-meter-width",screenMeterWidth+"px")}
function setView(view){currentView=view==="3d"?"3d":"2d";canvasArea.classList.toggle("view-3d",currentView==="3d");canvasArea.classList.toggle("view-2d",currentView==="2d");toolbar.querySelectorAll(".view-button").forEach(b=>{b.classList.toggle("active",b.dataset.view===currentView);b.setAttribute("aria-pressed",b.dataset.view===currentView?"true":"false")});plan.querySelectorAll(".planter-composite").forEach(object=>updatePlanter(object,object._plant,object._pot,object._stones));applyPlanTransform()}
canvasArea.addEventListener("pointerdown",event=>{if(!currentThemeName||event.target.closest(".garden-object,.plan-toolbar,.plan-scale,.plan-instructions,.garden-layer-manager")||event.button!==0)return;panState={id:event.pointerId,x:event.clientX,y:event.clientY,panX:planPanX,panY:planPanY};plan.classList.add("is-panning");canvasArea.setPointerCapture(event.pointerId);event.preventDefault()});canvasArea.addEventListener("pointermove",event=>{if(!panState||event.pointerId!==panState.id)return;planPanX=panState.panX+event.clientX-panState.x;planPanY=panState.panY+event.clientY-panState.y;applyPlanTransform()});function stopPlanPan(event){if(!panState||event.pointerId!==panState.id)return;panState=null;plan.classList.remove("is-panning")};canvasArea.addEventListener("pointerup",stopPlanPan);canvasArea.addEventListener("pointercancel",stopPlanPan);
toolbar.querySelectorAll(".view-button").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));
toolbar.querySelectorAll("[data-zoom]").forEach(b=>b.addEventListener("click",()=>{planZoom=Math.max(.65,Math.min(4,planZoom+(b.dataset.zoom==="in"?0.25:-0.25)));setView(currentView)}));
window.addEventListener("resize",()=>{plan.querySelectorAll(".garden-object").forEach(object=>{if(object.classList.contains("planter-composite"))updatePlanter(object,object._plant,object._pot,object._stones);else if(object._product)setObjectWidth(object,measuredWidth(object._product.name,object._product.category))});applyPlanTransform()});
canvasArea.addEventListener("click",e=>{if(e.target===canvasArea||e.target===plan||e.target===grid||e.target.classList.contains("ground-feature"))selectObject(null)});
document.querySelectorAll(".template-card").forEach(c=>{c.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();c.click()}})});
function exactProduct(name,cats){if(!name)return null;return PRODUCTS.find(p=>cats.indexOf(normCategory(p.category))>=0&&p.name.toLowerCase()===String(name).toLowerCase())||null}
function cleanPlacements(data){let list=Array.isArray(data.placements)?data.placements:[];if(!list.length&&(data.suggested_plant||data.suggested_pot))list=[{plant:data.suggested_plant,pot:data.suggested_pot,x:50,y:50}];return list.slice(0,6).map((e,i)=>{const plant=exactProduct(e.plant||e.suggested_plant,["indoor","outdoor"]),pot=exactProduct(e.pot||e.suggested_pot,["pots"]);if(!plant&&!pot)return null;const spot=nextPosition(i),sourceX=Math.max(10,Math.min(90,Number(e.x)||spot[0])),sourceY=Math.max(10,Math.min(90,Number(e.y)||spot[1]));return{plant:plant,pot:pot,stones:null,x:50+(sourceX-50)*.55,y:50+(sourceY-50)*.55,size:["small","medium","large"].indexOf(String(e.size))>=0?String(e.size):"medium"}}).filter(Boolean)}
function localLayout(){const plants=PRODUCTS.filter(p=>["indoor","outdoor"].indexOf(normCategory(p.category))>=0),pots=PRODUCTS.filter(p=>normCategory(p.category)==="pots"),spots=[[36,38],[50,50],[64,38],[38,62],[62,62]],n=Math.min(5,plants.length,pots.length),out=[];for(let i=0;i<n;i++)out.push({plant:plants[(i*3)%plants.length],pot:pots[i%pots.length],stones:null,x:spots[i][0],y:spots[i][1]});return out}
function placeLayout(items){items.forEach(x=>{if(x.pot)createPlanter(x.plant,x.pot,x.stones,{x:x.x,y:x.y,size:x.size},false);else{if(x.plant)addLoose(x.plant,{x:x.x,y:x.y});if(x.stones)addLoose(x.stones,{x:x.x+8,y:x.y+5})}})}
function suggestion(data,offline){const b=document.getElementById("aiSuggestion"),tip=data.layout_tip||"Group planters in odd numbers, leave a clear route, and keep taller plants toward the back.",dim=data.dimension_guide||"Use the one metre grid to estimate spacing.",balance=data.scene_balance||"Balance planted areas with open space.",focal=data.focal_point||"Use a taller mixed planter as a focal point.";b.innerHTML="<div class='flex flex-col gap-1.5'><span><b>"+(offline?"Local plan":"AI garden plan")+":</b> "+escapeHtml(tip)+"</span><span class='text-secondary bg-surface-container-low px-3 py-1 rounded-md mt-1 inline-block border border-secondary/20'><b>Scale:</b> "+escapeHtml(dim)+"</span><span><b>Balance:</b> "+escapeHtml(balance)+" <b>Focal:</b> "+escapeHtml(focal)+"</span></div>";b.classList.remove("hidden")}
async function triggerAIDecorate(){if(!currentThemeName)return;aiButton.innerHTML='<span class="material-symbols-outlined text-[18px] animate-spin">refresh</span> Planning...';aiButton.disabled=true;loader.classList.remove("hidden");loader.classList.add("flex");try{const r=await fetch("visualize_garden.php",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({theme:currentThemeName})}),result=await r.json();if(!r.ok||result.status!=="success"||!result.data)throw Error(result.message||"Planner unavailable");const data=result.data;let items=cleanPlacements(data);if(!items.length)items=localLayout();plan.querySelectorAll(".garden-object").forEach(n=>n.remove());selectObject(null);placeLayout(items);suggestion(data,false)}catch(err){console.warn("AI unavailable; using local inventory planner.",err);const items=localLayout();plan.querySelectorAll(".garden-object").forEach(n=>n.remove());selectObject(null);placeLayout(items);suggestion({layout_tip:"Planters are grouped around an open route through the garden.",dimension_guide:"Use the grid as a guide for real-world spacing.",scene_balance:"This local plan balances planting with open space.",focal_point:"Pebbles are optional. Drop a bag onto a pot to add them."},true)}finally{loader.classList.remove("flex");loader.classList.add("hidden");aiButton.innerHTML='<span class="material-symbols-outlined text-[18px]">auto_awesome</span> Generate Garden Plan';aiButton.disabled=false}}
function clearCanvas(){plan.querySelectorAll(".garden-object,.ground-feature").forEach(n=>n.remove());document.querySelectorAll(".template-card").forEach(c=>c.classList.remove("active"));plan.style.display="none";plan.style.backgroundImage="none";canvasArea.style.touchAction="auto";canvasArea.style.backgroundImage="none";grid.style.display="none";placeholder.style.display="block";document.getElementById("aiSuggestion").classList.add("hidden");currentThemeName="";selectedObject=null;selectedLayer="";renderLayerManager();aiButton.disabled=true}
const inventoryList=document.getElementById("inventoryList");
if(inventoryList){const enableDrag=()=>inventoryList.querySelectorAll("button[data-product-id]").forEach(button=>{if(button.dataset.dragReady==="true")return;button.dataset.dragReady="true";button.draggable=true;button.addEventListener("dragstart",event=>{const product=PRODUCTS.find(item=>String(item.id)===button.dataset.productId);if(!product||!event.dataTransfer)return;event.dataTransfer.effectAllowed="copy";event.dataTransfer.setData("text/plain",String(product.id))})});enableDrag();new MutationObserver(enableDrag).observe(inventoryList,{childList:true,subtree:true});plan.addEventListener("dragover",event=>event.preventDefault());plan.addEventListener("drop",event=>{event.preventDefault();const id=event.dataTransfer&&event.dataTransfer.getData("text/plain"),product=PRODUCTS.find(item=>String(item.id)===id);if(!product)return;const bounds=plan.getBoundingClientRect(),x=Math.max(5,Math.min(95,(event.clientX-bounds.left)/bounds.width*100)),y=Math.max(7,Math.min(93,(event.clientY-bounds.top)/bounds.height*100)),target=findObjectAt(event.clientX,event.clientY,null),dropped=addLoose(product,{x,y});if(target)combineObjects(dropped,target)})}
window.addToCanvas=addToCanvas;window.loadTemplate=loadTemplate;window.triggerAIDecorate=triggerAIDecorate;window.clearCanvas=clearCanvas;window.setGardenView=setView;aiButton.innerHTML='<span class="material-symbols-outlined text-[18px]">auto_awesome</span> Generate Garden Plan';const guide=document.getElementById("visualizerGuide"),closeGuide=document.getElementById("closeVisualizerGuide");if(guide&&closeGuide&&!sessionStorage.getItem("greenprintVisualizerGuideSeen")){guide.classList.remove("hidden");guide.classList.add("flex")}if(closeGuide)closeGuide.addEventListener("click",()=>{guide.classList.add("hidden");guide.classList.remove("flex");sessionStorage.setItem("greenprintVisualizerGuideSeen","1")});
})();

